In [2]:
import numpy as np
#accessing array with index position
arr = np.array([3,6,8,9])
print(arr[1])

6


In [4]:
#Add 
arr = np.array([3,6,8,9])
print(arr[1]+arr[0]-arr[2])

1


In [18]:
#access
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,2])

xyz = np.array([[[100,200,300],[400,500,600]],[[700,800,900],[150,250,350]]])
print(xyz[0,1,2])

9
600


In [20]:
#string
arr = np.array([1,2,3,4],dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [22]:
#int
arr = np.array([1,2,3,4],dtype = 'i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [24]:
#float
arr = np.array([1,2,3,4],dtype = 'f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [26]:
#bool
arr = np.array([1,2,3,4],dtype = 'b')
print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [28]:
#float to int
arr = np.array([[1.2,2.3,3.4],[4.5,5.6,6.7]])
print(arr.astype('i'))
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
float64


In [30]:
#int to bool
arr = np.array([0,2,3])
print(arr.astype('bool'))
print(arr.dtype)

[False  True  True]
int64


In [32]:
#copy()method
arr = np.array([1,2,3,4,])
x = arr.copy()
print(x)

[1 2 3 4]


In [34]:
#changing index position
arr[0] =43
print(arr)

[43  2  3  4]


In [36]:
#view()
arr = np.array([1,2,3,4,])
y = arr.view()
print(y)

[1 2 3 4]


In [38]:
#shape 
arr = np.array([[1,2,3],[2,4,5]])
print(arr)
arr.shape

[[1 2 3]
 [2 4 5]]


(2, 3)

In [46]:
##Reshaping of an array
#converting 1D array to 2D
arr = np.array([1,2,3,4,5,6,#])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [52]:
#1D to 3D
x = np.array([1,2,3,4,5,6,7,8])
print(x.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
#addition of two arrays
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [56]:
#subtraction
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [58]:
#multiplication
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [60]:
#division
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [62]:
#exponential
print(np.exp(x))
print(np.exp(y))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[ 148.4131591   403.42879349]
 [1096.63315843 2980.95798704]]


In [64]:
#sort()
arr = np.array([9,8,3,2,1])
print(np.sort(arr))

[1 2 3 8 9]


In [66]:
#slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

print(arr[5:])

print(arr[:5])


[2 3 4 5]
[6 7]
[1 2 3 4 5]


In [68]:
#negative
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:-1])

print(arr[:-4])

print(arr[-6:-4])

[1 2 3 4 5 6]
[1 2 3]
[2 3]
