In [5]:
!pip install numpy

In [8]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
#2D
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
#3d
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#initial place holders
#2D
np.zeros((1,2))

array([[0., 0.]])

In [16]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [40]:
#create an array of evenly spaced values(stepvalues)
a = np.arange(10,25,3)
print(a)

[10 13 16 19 22]


In [34]:
#array of evenly spaced values
uni = np.linspace(110,80,10)
print(uni)

[110.         106.66666667 103.33333333 100.          96.66666667
  93.33333333  90.          86.66666667  83.33333333  80.        ]


In [38]:
a = np.array([[[3,5,6],[4,6,7]],
              [[3,5,6],[4,6,7]],
              [[6,6,4],[4,8,9]]])
print(a)

[[[3 5 6]
  [4 6 7]]

 [[3 5 6]
  [4 6 7]]

 [[6 6 4]
  [4 8 9]]]


In [42]:
import numpy as np
a = np.array([[[1,5],[8,19]],[[35,52],[80,90]]])
print(a)

[[[ 1  5]
  [ 8 19]]

 [[35 52]
  [80 90]]]


In [44]:
a = np.array([[9,0],[9,0]])
print(a)

[[9 0]
 [9 0]]


In [46]:
a = np.array([[[30,40],[90,40]],[[30,30],[60,60]]])
print(a)
a.ndim

[[[30 40]
  [90 40]]

 [[30 30]
  [60 60]]]


3

In [48]:
#creating random arrays
np.random.randint([[[10,20],[2,6]],[[30,40],[20,10]]])

array([[[ 8,  5],
        [ 0,  3]],

       [[ 1, 11],
        [16,  7]]])

In [50]:
#creating random arrays
np.random.random((6,8))

array([[0.45893277, 0.80507523, 0.99440761, 0.47670238, 0.95372598,
        0.04132942, 0.64875421, 0.54373024],
       [0.70590765, 0.4094656 , 0.0586604 , 0.98470781, 0.70972713,
        0.67242509, 0.65853816, 0.56431741],
       [0.67841203, 0.83893147, 0.53324107, 0.99531971, 0.98720289,
        0.92381606, 0.90613646, 0.03263664],
       [0.31595881, 0.45860767, 0.65595915, 0.29731078, 0.3704855 ,
        0.31344613, 0.93684672, 0.71202708],
       [0.16925895, 0.05057274, 0.79665017, 0.20259256, 0.01693029,
        0.7540068 , 0.45204178, 0.92817805],
       [0.2558698 , 0.30198627, 0.9758742 , 0.12988901, 0.99780019,
        0.76214788, 0.60257308, 0.18378909]])

In [58]:
a=np.full((2),5)
print(a)

[5 5]


In [62]:
a = np.full((10,20),5)
print(a)

[[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]]


In [64]:
a=np.full((2,3,4),6)
print(a)

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


In [74]:
#shape of an array
a = np.array([
    [[3,4],[50,4]],
    [[30,3],[75,6]]
    ])
print(a)
print(a.shape)

[[[ 3  4]
  [50  4]]

 [[30  3]
  [75  6]]]
(2, 2, 2)


In [76]:
#size of an array
a = np.array([
    [[3,4],[50,4]],
    [[30,3],[75,6]]
    ])
print(a)
print(a.size)

[[[ 3  4]
  [50  4]]

 [[30  3]
  [75  6]]]
8


In [78]:
#len of an array
a = np.array([
    [[3,4],[50,4]],
    [[30,3],[75,6]]
    ])
print(a)
len(a)

[[[ 3  4]
  [50  4]]

 [[30  3]
  [75  6]]]


2